version: '3.10'

services:
  front:
    build:
      context: ./front
    ports:
      - "8000:8000"
    environment:
      - ARTIFACT_STORE_URI=${ARTIFACT_STORE_URI}
      - API_URL=http://api:5000  # Assuming API service name is 'api'
    depends_on:
      - api

  api:
    build:
      context: ./api
    ports:
      - "5000:5000"
    environment:
      - ARTIFACT_STORE_URI=${ARTIFACT_STORE_URI}
      - AWS_ACCESS_ID=${AWS_ACCESS_ID}
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - BACKEND_STORE_URI=${BACKEND_STORE_URI}
    depends_on:
      - mlflow
    links:
      - mlflow:mlflow  # Linking mlflow service

  mlflow:
    build:
      context: ./mlflow
    ports:
      - "7000:7000"
    environment:
      - ARTIFACT_STORE_URI=${ARTIFACT_STORE_URI}
      - AWS_ACCESS_ID=${AWS_ACCESS_ID}
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - BACKEND_STORE_URI=${BACKEND_STORE_URI}
    depends_on:
      - database

  database:
    image: "postgres:13"
    environment:
      - POSTGRES_USER=yourusername
      - POSTGRES_PASSWORD=yourpassword
      - POSTGRES_DB=mlflow

