version: '3.10'

services:
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    environment:
      - PORT=8501

  mlflow:
    build:
      context: ./mlflow
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - BACKEND_STORE_URI=${BACKEND_STORE_URI}
      - ARTIFACT_STORE_URI=${ARTIFACT_STORE_URI}
      - PORT=5000

  back:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
